### PR TITLE
Fix bugs, compiler warnings and add tests

### LINKED ISSUE #13: Error case of `read_to_string` not handled
```
warning: unused `std::result::Result` which must be used
   --> src/decoder/mod.rs:276:9
    |
276 |         self.reader.read_to_string(&mut out);
```

### LINKED ISSUE #28: Panic on malformed input: Index out of range in Decoder::expand_strip
Feed one of the attached sample files to the standard input of the following code to trigger a panic:

```rust
extern crate afl;
extern crate tiff;

use tiff::decoder::{Decoder};
use std::io::Cursor;

fn main() {
    afl::read_stdio_bytes(|data| {
        let cursor = Cursor::new(&data);
        if let Ok(mut decoder) = Decoder::new(cursor) {
            decoder.read_image();
        }
    });
}
```
Samples triggering the panic: [tiff-oor-panics.zip](https://github.com/PistonDevelopers/image-tiff/files/2908118/tiff-oor-panics.zip)

Backtrace:

```
thread 'main' panicked at 'index 884062630 out of range for slice of length 23707', src/libcore/slice/mod.rs:2349:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2349
   9: <tiff::decoder::Decoder<R>>::expand_strip
  10: <tiff::decoder::Decoder<R>>::read_image
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  13: afl::read_stdio_bytes
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: _start
Aborted
```

Found with [AFL.rs](https://github.com/rust-fuzz/afl.rs). Tested on version 0.2.2

### LINKED ISSUE #29: Memory exhaustion and crash on malformed input
Decoding any of the attached files triggers a crash with the following error message: `memory allocation of 136902082592 bytes failedAborted`

[tiff-oom-crashes.zip](https://github.com/PistonDevelopers/image-tiff/files/2908135/tiff-oom-crashes.zip)

The exact reproduction code can be found in #28. Found via [AFL.rs](https://github.com/rust-fuzz/afl.rs), tested on `image-tiff` version 0.2.2

Most decoding libraries face this issue at some point. This is usually solved by limiting the amount of allocated memory to some sane default, and letting people override it if they're really dealing with enormous amounts of data. In Rust we can easily allow the API user to override these limits via the [builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html).

See https://libpng.sourceforge.io/decompression_bombs.html for more info on how a similar issue was solved in libpng. See also the [Limits](https://docs.rs/flif/0.3.0/flif/struct.Limits.html) struct from flif crate.

### LINKED ISSUE #30: Tests fail with "index out of bounds"
Currently the tests fail with an index out of bounds error, this is probably a bug introduced in #26 that could only be discovered with the tests from #23. 

```
running 1 test
test decoder::stream::test::test_packbits ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/decode_images-564f01fb7ded3313

running 6 tests
test test_gray_u8 ... ok
test test_rgb_u8 ... ok
test test_string_tags ... ok
test test_gray_u16 ... ok
test test_decode_data ... ok
test test_rgb_u16 ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/encode_images-b9c0207f836596cd

running 5 tests
test test_gray_u8_roundtrip ... ok
test test_rgb_u8_roundtrip ... ok
test test_gray_u16_roundtrip ... ok
test encode_decode ... ok
test test_rgb_u16_roundtrip ... FAILED

failures:

---- test_rgb_u16_roundtrip stdout ----
thread 'test_rgb_u16_roundtrip' panicked at 'index out of bounds: the len is 19 but the index is 19', /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2463:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test_rgb_u16_roundtrip

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test encode_images'
```

### LINKED ISSUE #31: Infinite loop on malformed input
Decoding [these samples](https://github.com/PistonDevelopers/image-tiff/files/2911611/tiff-inf-loop.zip) with `Decoder.read_image()` causes 100% CPU usage. I've run it for 10 minutes before giving up. The code is likely entering an infinite loop.

The exact reproduction code can be found in #28. Found via [AFL.rs](https://github.com/rust-fuzz/afl.rs), tested on `image-tiff` version 0.2.2

### PR DESCRIPTION
**Pull request by birktj**
This PR adds a `Limits` struct to fix the memory exhaustion bug in #29, this changes the public API slightly, because `ifd::Entry::val` now also needs a `Limits` parameter. It adds some array bounds checking for indices that directly come from the tiff file. While I was at it I also fixed #13 by changing `Decoder::read_string` to return a `TiffResult` instead of a `FromUtf8Error` result. I also fixed some smaller compiler and clippy warnings. 

I added the samples from #28, #29 and #31 as new tests, thank you @Shnatsel!

This will fix #13, fix #28, fix #29, fix #30 and fix #31.

@Robzz and @HeroicKatora what do you think of this?

### CODE REVIEW

File: src/decoder/mod.rs [hunk 1]
```diff
@@ -95,13 +126,36 @@ struct StripDecodeState {
...
+#[derive(Clone, Debug)]
+pub struct Limits {
+    /// The maximum size of any `DecodingResult` in bytes, the default is 
+    /// 256MiB. If the entire image is decoded at once, then this will
+    /// be the maximum size of the image. If it is decoded one strip at a
+    /// time, this will be the maximum size of a strip.
+    decoding_buffer_size: u64,
+    /// The maximum size of any ifd value in bytes, the default is 
+    /// 1MiB.
+    ifd_value_size: u64,
```
Comment (Shnatsel) [inline src/decoder/mod.rs]: Any particular reason why this is `u64` and not `usize`? You cannot really have a u64-sized buffer on a 32-bit platform.

**Comment by Shnatsel** [comment]
Thanks for fixing these so quickly! This has unblocked further fuzzing which found at least one more panic: #33

File: src/decoder/mod.rs [hunk 2]
```diff
@@ -28,7 +27,25 @@ pub enum DecodingResult {
...
+        if size as u64 > limits.decoding_buffer_size {
+            Err(TiffError::LimitsExceeded)
+        }
+        else {
+            Ok(DecodingResult::U8(vec![0; size]))
+        }
+    }
+
+    fn new_u16(size: usize, limits: &Limits) -> TiffResult<DecodingResult> {
+        if size as u64*2 > limits.decoding_buffer_size {
```
Comment (HeroicKatora) [inline src/decoder/mod.rs]: This one should probably be `size as u64 > limits.decoding_buffer_size/2` otherwise the mult may overflow, or use `checked_mul` instead.

Comment (HeroicKatora) [reply src/decoder/mod.rs]: Overall, I'm not sure if the case of `usize == u32` is handled properly for all the multiplications everywhere (i.e. doesn't overflow them).

File: src/decoder/mod.rs (hunk 1 above)
Comment (birktj) [reply src/decoder/mod.rs]: Not really, I just took from the `Limits` struct in the `png` crate, but you are right `usize` would be a better fit.

**Comment by birktj** [comment]
@HeroicKatora I have fixed the possibly overflowing multiplication and changed the limits to `usize`. Do you think I need to change anything else or are we good to go?

**Comment by birktj** [comment]
@HeroicKatora @Robzz @bvssvni friendly ping. Would it be possible to look at this so that we can eventually release a new version of the library with the newly merged PRs?

**Comment by HeroicKatora** [comment]
Just now realized that during converting to `TiffResult`, the line you changed here https://github.com/PistonDevelopers/image-tiff/pull/32/files#diff-ee033e65f37f7717cb17dc37bc71de6bL301 was actually a bug as the error was ignored. Good job :+1: We should probably do a stability release sometime soon. Want to merge this today if no further concerns appear.
